language: python
sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: nightly
    - python: pypy
    - python: pypy3

install:
  - pip install tox

script:
  - tox -e py

cache:
  - pip
